name: 自动群发邮件

on:
  schedule:
    # 每月 1 号 17:00 UTC 运行 ≈ 每月 2 号 北京时间 01:00 运行
    - cron: "0 17 1 * *"
  workflow_dispatch:  # 支持手动触发

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # 可根据需要调整为具体的版本

      # Step 3: 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 使用 requirements.txt 管理依赖

      # Step 4: 运行邮件发送脚本
      - name: Run email sender script
        env:
          EMAIL_CONFIG: ${{ secrets.EMAIL_CONFIG }}
          TG_ID: ${{ secrets.TG_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        run: |
          python "send_email.py"
